#!/usr/bin/env python3
"""Generates addon/shadow_page.conf: the JV-880 shadow-mode GUI for force-shadow.

DRAFT / MOCKUP. Layout is computed here (see docs/SHADOW-GUI-PROPOSAL.md).
Keys are the real jv880 plugin keys (nvram_tone_<n>_*, nvram_patchCommon_*,
macro_*) and the envelope graphs, which use force-shadow's env widget in
tkey/lkey mode (nvram_tone_<n>_penvtime%d / penvlevel%d sibling knobs).

  python3 scripts/gen_shadow_page.py [--out path]
"""
import argparse, json
from pathlib import Path

ap = argparse.ArgumentParser()
ap.add_argument("--out", default=str(Path(__file__).resolve().parent.parent / "addon" / "shadow_page.conf"))
OUT = Path(ap.parse_args().out)

ARGS = [
 ("module-dir flag", "--module-dir"), ("module directory (module.json/roms source)", "/media/662522/AddOns/ForceJV880"),
 ("ctrl-sock flag", "--ctrl-sock"), ("control socket path", "/tmp/jv880_ctrl.sock"),
 ("control-channel flag", "--control-channel"), ("Q-Link control channel (1-16)", "1"),
 ("mix-slot flag", "--mix-slot"), ("ForceAudioIn voice slot (0-3; 1, not 0, to avoid Maze Voice's own default)", "1")]
ARGS_JSON = json.dumps([{"NAME": n, "VALUE": v} for n, v in ARGS], separators=(",", ":"))

HEADER = f'''# force-jv880 shadow-mode page -- GENERATED by scripts/gen_shadow_page.py, edit that instead.
# Style: Roland JV-880 front panel -- yellow-green LCD-backlight accent on charcoal, dotted-arc knobs.
page=2
ctrl_sock=/tmp/jv880_ctrl.sock
display_name=JV-880
style=lcd
frame_style=plain
topbar_style=display
theme_display_bg=a3c13c
theme_display_cell=98b735
theme_display_ink=0a1004
theme_display_off=8aa62c
theme_display_bezel=101210
int_values=1
theme_bg=232527
theme_panel=2a2d2f
theme_line=42484a
theme_ink=e2e4de
theme_ink_dim=8f9490
theme_ink_faint=5c625f
theme_accent=b9d94a
theme_accent_hi=e4f38c
theme_knob_face=1a1c1d
theme_knob_ring=3b4143
theme_bar=1b1d1e
theme_seg_active=b9d94a
theme_seg_inactive=1d1f20
theme_seg_active_tx=1a1c1d
theme_btn_text=1a1c1d
theme_well=1d1f20
theme_knob_off=4a5052
theme_tab_on=303a1a
theme_lcd=202b12
engine_process_name=jv_host
engine_nsmodule_path=/media/662522/AddOns/ForceJV880/NSMODULE.json
engine_dirname=ForceJV880
engine_arguments_json={ARGS_JSON}
'''

BODY_Y, BODY_H, L, R = 88, 636, 36, 1244
BANKS_TAB = 6
T = "nvram_tone_%d_"
PC = "nvram_patchCommon_"
lines = []
emit = lines.append

def frame(x, y, w, h, t): emit(f'frame x={x} y={y} w={w} h={h} title="{t}"')
def knob(cx, cy, r, lb, key, lo, hi, pct=50): emit(f'knob cx={cx} cy={cy} r={r} label="{lb}" key={key} min={lo} max={hi} pct={pct}')
def toggle(cx, cy, lb, key): emit(f'toggle cx={cx} cy={cy} label="{lb}" key={key} on=0')
def enum_h(cx, cy, lb, key, opts, sw): emit(f'enum_h cx={cx} cy={cy} label="{lb}" key={key} options="{",".join(opts)}" active=0 sw={sw}')
def row(n, x0, x1):
    s = (x1 - x0) / n
    return [round(x0 + s * (i + .5)) for i in range(n)]

def topbar():
    emit(f'readout cx=350 cy=36 w=300 h=44 label="" get=bank_name goto={BANKS_TAB}')
    emit('stepper cx=775 cy=36 w=490 h=44 label="" key=preset get=patch_name idx=preset count=preset_count min=0 max=127 numbered=1')

def play_tab():
    emit('[tab PLAY]'); topbar()
    # OUTPUT/MACROS grew from h=300 to h=330 (and EFFECT SENDS' start from
    # +312 to +342) to fit the new DEST row above the existing two knob
    # rows without the bottom row's value text running past the frame edge.
    frame(L, BODY_Y, 380, 330, "OUTPUT")
    # Voice on/off removed here (redundant with the ENGINE power switch);
    # DEST replaces the old L/R/L+R channel notion with the destination
    # bus/channel a voice lands on (see forceAudioInject.h): I1, I2, I1+2
    # (stereo into Audio-In 1/2), O3, O4, O3+4 (stereo into Out 3/4) - I/O
    # prefix kept short (no "IN"/"OUT") so all 6 options still fit the
    # frame at a legible width; "+" not "," between paired numbers only
    # because enum_h's options list is itself comma-delimited - see web
    # GUI for the spelled-out "IN1,2"/"OUT3,4" labels.
    enum_h(L + 190, BODY_Y + 60, "DEST", "mix.dest_idx", ["I1", "I2", "O3", "O4", "I1+2", "O3+4"], 60)
    xs = row(2, L, L + 380)
    knob(xs[0], BODY_Y + 140, 30, "VOICE VOL", "mix.gain", 0, 150, 40)
    knob(xs[1], BODY_Y + 140, 30, "OCTAVE", "octave_transpose", -4, 4)
    knob(xs[0], BODY_Y + 250, 30, "PATCH LVL", PC + "patchlevel", 0, 127)
    knob(xs[1], BODY_Y + 250, 30, "PATCH PAN", PC + "patchpan", 0, 127)
    frame(432, BODY_Y, 812, 330, "MACROS  (offset all tones)")
    xs = row(4, 432, 1244)
    for cx, (lb, k, lo, hi) in zip(xs, [("CUTOFF", "cutoff", 0, 127), ("RESO", "resonance", 0, 127), ("TVF DEPTH", "tvf_env_depth", -63, 63), ("LFO DEPTH", "lfo_depth", -63, 63)]):
        knob(cx, BODY_Y + 110, 30, lb, "macro_" + k, lo, hi)
    for cx, (lb, k) in zip(xs, [("ATTACK", "attack"), ("DECAY", "decay"), ("SUSTAIN", "sustain"), ("RELEASE", "release")]):
        knob(cx, BODY_Y + 250, 30, lb, "macro_" + k, 0, 127)
    frame(L, BODY_Y + 342, R - L, BODY_H - 342, "EFFECT SENDS")
    xs = row(2, L, L + 500)
    knob(xs[0], BODY_Y + 342 + 130, 34, "REVERB", PC + "reverblevel", 0, 127)
    knob(xs[1], BODY_Y + 342 + 130, 34, "CHORUS", PC + "choruslevel", 0, 127)
    # tone on/off strip: at-a-glance, like the JV-880 tone LEDs
    for i, cx in enumerate(row(4, 560, R)):
        toggle(cx, BODY_Y + 342 + 190, f"TONE {i+1}", (T % i) + "toneswitch")

def patch_tab():
    emit('[tab PATCH]'); topbar()
    hw = (R - L - 16) // 2
    frame(L, BODY_Y, hw, 300, "CONTROL")
    xs = row(3, L, L + hw)
    knob(xs[0], BODY_Y + 96, 30, "ANALOG FEEL", PC + "analogfeel", 0, 127)
    toggle(xs[1], BODY_Y + 100, "VEL SWITCH", PC + "velocityswitch")
    toggle(xs[2], BODY_Y + 100, "SOLO LEGATO", PC + "sololegato")
    enum_h(xs[1], BODY_Y + 232, "KEY ASSIGN", PC + "keyassign", ["POLY", "SOLO"], 80)
    frame(L + hw + 16, BODY_Y, hw, 300, "BEND / PORTAMENTO")
    xs = row(3, L + hw + 16, R)
    knob(xs[0], BODY_Y + 100, 30, "BEND UP", PC + "bendrangeup", 0, 12)
    knob(xs[1], BODY_Y + 100, 30, "BEND DOWN", PC + "bendrangedown", 0, 48)
    knob(xs[2], BODY_Y + 100, 30, "PORTA TIME", PC + "portamentotime", 0, 127)
    toggle(xs[0], BODY_Y + 232, "PORTA", PC + "portamentoswitch")
    enum_h(xs[1], BODY_Y + 232, "MODE", PC + "portamentomode", ["NORM", "LEGATO"], 66)
    enum_h(xs[2], BODY_Y + 228, "TYPE", PC + "portamentotype", ["TIME", "RATE"], 60)
    y2 = BODY_Y + 312
    fh = BODY_H - 312
    frame(L, y2, hw, fh, "REVERB")
    xs = row(3, L, L + hw)
    enum_h(L + hw // 2, y2 + 70, "TYPE", PC + "reverbtype", ["ROOM1", "ROOM2", "STAGE1", "STAGE2", "HALL1", "HALL2", "DELAY", "PAN-DLY"], 62)
    knob(xs[0], y2 + 190, 30, "LEVEL", PC + "reverblevel", 0, 127)
    knob(xs[1], y2 + 190, 30, "TIME", PC + "reverbtime", 0, 127)
    knob(xs[2], y2 + 190, 30, "FEEDBACK", PC + "reverbfeedback", 0, 127)
    frame(L + hw + 16, y2, hw, fh, "CHORUS")
    xs = row(5, L + hw + 16, R)
    enum_h(L + hw + 16 + hw // 2, y2 + 70, "TYPE", PC + "chorustype", ["CHORUS1", "CHORUS2", "FLANGER"], 90)
    for cx, (lb, k) in zip(xs, [("LEVEL", "choruslevel"), ("DEPTH", "chorusdepth"), ("RATE", "chorusrate"), ("FEEDBACK", "chorusfeedback")]):
        knob(cx, y2 + 190, 28, lb, PC + k, 0, 127)
    toggle(xs[4], y2 + 190, "OUT", PC + "chorusoutput")

def envcol(x, w, y, h, title, kind, n):
    """Draggable envelope graph. kind: penv (pitch, signed levels), tvfenv (filter),
    tvaenv (amp, 3 levels). The T/L values live in hidden knobs (read back from the
    engine like any other param); dragging a point sets its time (x) and level (y)."""
    t = T % (n - 1)
    lo, hi, nl = (-63, 63, 4) if kind == "penv" else (0, 127, 3 if kind == "tvaenv" else 4)
    frame(x, y, w, h, title)
    emit(f'env cx={x + w//2} cy={y + 46 + (h - 62) // 2} w={w - 32} h={h - 62} prefix={t}{kind} '
         f'tkey={t}{kind}time%d lkey={t}{kind}level%d lmin={lo} lmax={hi} nl={nl}')
    for i in range(4):
        emit(f'knob cx=0 cy=0 r=1 label="T{i+1}" key={t}{kind}time{i+1} min=0 max=127 pct=50 hidden=1')
        if i < nl:
            emit(f'knob cx=0 cy=0 r=1 label="L{i+1}" key={t}{kind}level{i+1} min={lo} max={hi} pct=50 hidden=1')

def tone_tab(n):
    t = T % (n - 1)
    emit(f'[tab TONE {n}]'); topbar()
    ah = 150
    frame(L, BODY_Y, R - L, ah, f"TONE {n}  WAVE / PITCH")
    cy = BODY_Y + 76
    toggle(100, cy, "TONE", t + "toneswitch")
    enum_h(300, cy + 8, "", t + "wavegroup", ["INT-A", "INT-B", "EXP-A", "EXP-B"], 64)
    knob(520, cy, 24, "WAVE #", t + "wavenumber", 0, 255)
    toggle(650, cy, "FXM", t + "fxmswitch")
    knob(780, cy, 24, "FXM DEPTH", t + "fxmdepth", 1, 16)
    knob(930, cy, 24, "COARSE", t + "pitchcoarse", -48, 48)
    knob(1070, cy, 24, "FINE", t + "pitchfine", -50, 50)
    cw = (R - L - 32) // 3
    y = BODY_Y + ah + 12
    eh = 250
    for i, (title, mock) in enumerate([("PITCH ENV", "penv"), ("FILTER ENV", "tvfenv"), ("AMP ENV", "tvaenv")]):
        envcol(L + i * (cw + 16), cw, y, eh, title, mock, n)
    y3 = y + eh + 12
    hw = (R - L - 16) // 2
    for j, lf in enumerate((1, 2)):
        x = L + j * (hw + 16)
        frame(x, y3, hw, BODY_Y + BODY_H - y3, f"LFO {lf}")
        enum_h(x + 190, y3 + 62, "", f"{t}lfo{lf}form", ["TRI", "SIN", "SAW", "SQU", "RND1", "RND2"], 54)
        if lf == 1: toggle(x + hw - 60, y3 + 58, "SYNC", t + "lfo1synchro")
        xs = row(6, x, x + hw)
        for cx, (lb, k, lo, hi) in zip(xs, [("RATE", "rate", 0, 127), ("DELAY", "delay", 0, 127), ("FADE", "fadetime", 0, 127),
                                            ("PITCH", "pitchdepth", -63, 63), ("FILTER", "tvfdepth", -63, 63), ("AMP", "tvadepth", -63, 63)]):
            knob(cx, y3 + 134, 20, lb, f"{t}lfo{lf}{k}", lo, hi)

def banks_tab():
    emit('[tab BANKS]'); topbar()
    frame(L, BODY_Y, 724, BODY_H, "BANKS / EXPANSIONS")
    emit(f'list x={L+16} y={BODY_Y+44} w=692 h=580 key=bank_index items=bank_list sel=bank_index cols=2 rows=6 th=62 gap=10 jump=1 colmajor=0 numbered=0 scale=1.5')
    frame(776, BODY_Y, R - 776, BODY_H, "PATCHES")
    emit(f'list x=792 y={BODY_Y+44} w=436 h=580 key=preset items=patch_list sel=preset cols=2 rows=14 th=33 gap=3 jump=0 colmajor=1 numbered=1 scale=1.5')

play_tab(); patch_tab()
for n in range(1, 5): tone_tab(n)
banks_tab()
OUT.write_text(HEADER + "\n" + "\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(lines)} lines)")
